# Generated by Django 3.2.23 on 2023-11-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=150)),
                ('ratings', models.IntegerField()),
            ],
        ),
    ]
